### ISSUE TITLE
solve duplicate genes ignored when mutated

### ISSUE THREAD

**Issue by IlanSchindler** [ahmedfgad/GeneticAlgorithmPython#164]
I kept running into a problem where the "allow_dupllicate_genes=False" just wasnt working. i started to step through the pygad code in debug and found this in all of the built in crossover functions:
` if (self.mutation_type is None) and (self.allow_duplicate_genes == False):`

Why is the allow_duplicate_genes ignored if you put in a mutation?

**Comment by ahmedfgad** [comment]
Thank you. This issue is already solved and will be pushed in the next release soon.

**Comment by dmark04** [comment]
Even in release 3.0.0 this issue seems to persist for me.

```python
import pygad
import numpy
import itertools

def mock_function(ga_instance, solution, sol_idx):
    return -1 * (solution[0] ** 2 + solution[1] ** 2)
range = [.1, 1.]
param_values = numpy.linspace(range[0], range[1], 10).tolist()
initial_population = list(itertools.product(param_values, param_values))

ga = pygad.GA(num_generations=100,
              num_parents_mating=10,
              gene_type=float,
              gene_space={'low': range[0], 'high': range[1]},
              fitness_func=mock_function,
              initial_population=initial_population,
              mutation_probability=0.2,
              allow_duplicate_genes=False,
              )
ga.run()

new_points = ga.population
unique_points = set([tuple(x) for x in new_points])
print(len(initial_population), len(new_points), len(unique_points))
print(f"Best solution is {ga.best_solution()[0]}.")
for point in new_points:
    for x in point:
        if not range[0] <= x <= range[1]:
            print(f"Point {point} is outside gene_space.")
    self.assertTrue(all(range[0] <= x <= range[1] for x in point))
self.assertEqual(len(initial_population), len(unique_points))
```

This example consistently produces points that are not unique and outside the `gene_space`.
Removing the mutation solves the uniqueness issue , in agreement with the bug above (also the `gene_space` is then respected).
Maybe you should add in the docs that mutation makes those two input parameters useless.

**Comment by ahmedfgad** [comment]
> Even in release 3.0.0 this issue seems to persist for me.
> 
> ```python
> import pygad
> import numpy
> import itertools
> 
> def mock_function(ga_instance, solution, sol_idx):
>     return -1 * (solution[0] ** 2 + solution[1] ** 2)
> range = [.1, 1.]
> param_values = numpy.linspace(range[0], range[1], 10).tolist()
> initial_population = list(itertools.product(param_values, param_values))
> 
> ga = pygad.GA(num_generations=100,
>               num_parents_mating=10,
>               gene_type=float,
>               gene_space={'low': range[0], 'high': range[1]},
>               fitness_func=mock_function,
>               initial_population=initial_population,
>               mutation_probability=0.2,
>               allow_duplicate_genes=False,
>               )
> ga.run()
> 
> new_points = ga.population
> unique_points = set([tuple(x) for x in new_points])
> print(len(initial_population), len(new_points), len(unique_points))
> print(f"Best solution is {ga.best_solution()[0]}.")
> for point in new_points:
>     for x in point:
>         if not range[0] <= x <= range[1]:
>             print(f"Point {point} is outside gene_space.")
>     self.assertTrue(all(range[0] <= x <= range[1] for x in point))
> self.assertEqual(len(initial_population), len(unique_points))
> ```
> 
> This example consistently produces points that are not unique and outside the `gene_space`. Removing the mutation solves the uniqueness issue , in agreement with the bug above (also the `gene_space` is then respected). Maybe you should add in the docs that mutation makes those two input parameters useless.


@dmark04, there are 2 issues:
1. The initial population has some duplicate genes. Yet, it is expected that the user will pass an initial population without duplicates.
2. You did not adjust the random mutation range. The default range is `-1` to `1`. Thus, it is very likely that the gene gets outside the specified range after mutation. You can solve it by setting `mutation_by_replacement=True`.

The 2 issues above are fixed in this code which works well without duplicates:
```python
import pygad
import numpy
import itertools

def mock_function(ga_instance, solution, sol_idx):
    return -1 * (solution[0] ** 2 + solution[1] ** 2)
range = [.1, 1.]
param_values = numpy.linspace(range[0], range[1], 10).tolist()
initial_population = list(itertools.product(param_values, param_values))

## Remove duplicates from the initial population.
for idx, sol in enumerate(initial_population):
    sol = list(sol)
    if sol[0] == sol[1]:
        sol[1] = sol[1] - 0.001
    initial_population[idx] = sol.copy()

ga = pygad.GA(num_generations=100,
              num_parents_mating=10,
              sol_per_pop=100,
              num_genes=2,
              gene_type=float,
              gene_space={'low': range[0], 'high': range[1]},
              fitness_func=mock_function,
              initial_population=initial_population,
              mutation_probability=0.2,
              allow_duplicate_genes=False,
              mutation_by_replacement=True
)
ga.run()

new_points = ga.population
unique_points = set([tuple(x) for x in new_points])
print(len(initial_population), len(new_points), len(unique_points))
print(f"Best solution is {ga.best_solution()[0]}.")
for point in new_points:
    for x in point:
        if range[0] > x > range[1]:
            print(f"Point {x} is outside gene_space ({range}).")
```

Please check it again and let us know if there are any issues.

**Comment by dmark04** [comment]
Hey thanks for the quick reply,
can confirm that your suggestions don't change anything for me , the population still only has about 35 unique genes instead of 100. and it still routinely produces values below 0.1 (even the solution is below 0.1).
So both problems are still there, you just removed the checks.
Also i fail to understand how my initial population has duplicate genes? how does a cartesian product of two times the same list produce non unique combinations? 
What you are doing is changing all points (x,y) where x=y. I find that a rather strange definition of uniqueness. why do you not require (x_i, y_j) != (x_l,x_k) for all i,j!=l,k ?

**Comment by ahmedfgad** [comment]
I am sure this code generates duplicate genes.
```python
range = [.1, 1.]
param_values = numpy.linspace(range[0], range[1], 10).tolist()
initial_population = list(itertools.product(param_values, param_values))
```

The if statement was just a demo. To respect the range specified, it could be edited:
```python
if sol[0] == sol[1]:
    if sol[1] < 0.101:
        sol[1] = sol[1] + 0.001
    else:
        sol[1] = sol[1] - 0.001
```

In your example, it is guaranteed that the generated genes by the library will be unique as long as the initial population is unique.

Thanks for your interest in PyGAD!

**Comment by dmark04** [comment]
Could you please (!!!) just execute the code you suggest? Clearly it does not do what you claim.
Modifying the if statement does seemingly fix the issue of genes being outside the desired `gene_space` . Although I find that weird. Why are there restrictions on the initial population imposed by the `gene_space` for the `gene_space` to work?
Also you again did not respond to any of my other questions? Please, I am putting quite some effort into making my points clear to you and writing detailed feedback. All I get back from you is the same answer all over that I pointed out now multiple times does NOT do what you claim, the code still generates mostly duplicates in the new population.

**Comment by ahmedfgad** [comment]
The code is working on my end without duplicates.

Until the library meets your expectations, I advise you to use an alternative to save your time.
